# fly.toml app configuration file generated for latamtvchannels on 2025-08-01T11:03:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'latamtvchannels'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 43001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
